[wokwi]
version = 1
pio_env = "esp32dev"
firmware = ".pio/build/esp32dev/firmware.bin"

[[chip]]
name = "hlk-ld2451"
binary = "radarchipemu/hlk_ld2451.chip.wasm"
sources = ["radarchipemu/hlk_ld2451.chip.c"]